import ventana

def ing():
    ventana.barraMenu.entryconfigure(1, label = "Data Base")
    ventana.datosMenu.entryconfigure(0, label = "Create")
    ventana.datosMenu.entryconfigure(1, label = "Exit")
    ventana.barraMenu.entryconfigure(2, label = "Language")
    ventana.IdiomaMenu.entryconfigure(0, label = "Spanish")
    ventana.IdiomaMenu.entryconfigure(1, label = "English")
    ventana.notebook.tab(ventana.pes1, text ="Trainings")  
    ventana.notebook.tab(ventana.pes2, text ="Weather")
    ventana.actividadLabel.config(text = "Sport: ")
    ventana.correr.config(text = "Running")
    ventana.bicicleta.config(text = "Bicycle")
    ventana.tiempoLabel.config(text = "Time: ")
    ventana.distanciaLabel.config(text = "Distance: ")
    ventana.botonInsertar.config(text = "Insert")
    ventana.botonLimpiar.config(text = "Reset")
    ventana.buscarLabel.config(text = "--------Search--------")
    ventana.botonBuscar.config(text = "Search")
    ventana.seleccionarProvincia.config(text = "Select a province:")
    ventana.botonProvincia.config(text = "Today's weather ")
    ventana.botonDetalle.config(text = "Weather 7 next days")
    
    
def esp():
    ventana.barraMenu.entryconfigure(1, label = "Base de datos")
    ventana.datosMenu.entryconfigure(0, label = "Crear")
    ventana.datosMenu.entryconfigure(1, label = "Salir")
    ventana.barraMenu.entryconfigure(2, label = "Idioma")
    ventana.IdiomaMenu.entryconfigure(0, label = "Español")
    ventana.IdiomaMenu.entryconfigure(1, label = "Inglés")
    ventana.notebook.tab(ventana.pes1, text ="Entrenamientos")
    ventana.notebook.tab(ventana.pes2, text ="El tiempo")  
    ventana.actividadLabel.config(text = "Actividad: ")
    ventana.correr.config(text = "Correr")
    ventana.bicicleta.config(text = "Bicicleta")
    ventana.tiempoLabel.config(text = "Tiempo: ")
    ventana.distanciaLabel.config(text = "Distancia: ")
    ventana.botonInsertar.config(text = "Insertar")
    ventana.botonLimpiar.config(text = "Limpiar")
    ventana.buscarLabel.config(text = "--------Buscar--------")
    ventana.botonBuscar.config(text = "Buscar")
    ventana.seleccionarProvincia.config(text ="Selecciona una provincia:")
    ventana.botonProvincia.config(text = "Tiempo de hoy")
    ventana.botonDetalle.config(text = "Tiempo 7 proximos dias")
   